---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "test-user"
  namespace: default
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: "test-user-full-access"
  namespace: default
rules:
  - apiGroups: ["", "extensions", "apps", "autoscaling"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["batch"]
    resources:
      - jobs
      - cronjobs
    verbs: ["*"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: "test-user-view"
  namespace: default
subjects:
  - kind: ServiceAccount
    name: "test-user"
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "test-user-full-access"
